### ISSUE TITLE
Just Black screen

### ISSUE THREAD

**Issue by Zumbalamambo** [NON906/HandVR#1]
It just shows a black screen. How do I use this?

**Comment by NON906** [comment]
It is written in README.md.
(Sorry for using Japanese.)

If you are still not sure, please answer the following:
- iOS or Android?
- Which Unity version?

**Comment by Zumbalamambo** [comment]
I tested it in Android... Unity v 2019.2.12

**Comment by Zumbalamambo** [comment]
@NON906  where are you detecting the hands? also i dont see the mediapipe dll file in the directory. Could you please try to clone your repository and try?

**Comment by NON906** [comment]
mediapipe dll is here: Assets/HandVR/HandVR/Plugins/Android
I tried clone and build. It worked here.

**Comment by Zumbalamambo** [comment]
Could you please share the apk file?
