### ISSUE TITLE
Cannot compile xcode build

### ISSUE THREAD

**Issue by jerryComo** [NON906/HandVR#2]
Hi !
I'm using Unity 2020.3.22f1 and cannot compile the xcode due to 1000+ errors. I think this may be because OpenGLES is no longer supported. I've tried to include it in the build phases with no success in both Xcode 13 and 14.

Do I need to use an older version of Unity & What are your recommended versions ?

{edit] I've noticed the HandMR folder is RED in the folder structure which means it is missing ? - I did click on the HandMr dialogue pop-up to download it. Something must have gone wrong there. It won't let me re-download it in unity though.

ok many thanks,

<img width="1123" alt="Screenshot 2022-10-04 at 16 32 27" src="https://user-images.githubusercontent.com/92852896/193863076-2d1d2d5c-1fc2-4651-abdb-059f18915e3e.png">

**Comment by NON906** [comment]
Hello,

This repository is no longer supported.
(I will change it to "Public archive" because this is confusing.)

Similar functions can be used in the following repositories, so please use them.
https://github.com/NON906/HandMR
